# Generated by Django 4.2.13 on 2024-08-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.CharField(default='not defined', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(default=None)),
                ('due_date', models.DateTimeField(default=None)),
                ('front_sheet', models.CharField(default='not defined', max_length=5)),
                ('c_wave', models.CharField(default='not defined', max_length=5)),
                ('middle_sheet', models.CharField(default='not defined', max_length=5)),
                ('b_wave', models.CharField(default='not defined', max_length=5)),
                ('back_sheet', models.CharField(default='not defined', max_length=5)),
                ('level', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('left_edge_cut', models.IntegerField(default=0)),
                ('middle_edge_cut', models.IntegerField(default=0)),
                ('right_edge_cut', models.IntegerField(default=0)),
                ('component_type', models.CharField(default='not defined', max_length=5)),
                ('quantity', models.IntegerField(default=0)),
                ('production_quantity', models.IntegerField(default=0)),
                ('edge_type', models.CharField(default='not defined', max_length=5)),
                ('order_status', models.CharField(default='not defined', max_length=5)),
                ('excess_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_optimization.csvfile')),
            ],
        ),
        migrations.CreateModel(
            name='PlanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_quantity', models.IntegerField(default=0)),
                ('out', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_optimization.orderlist')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blade_1', models.ManyToManyField(related_name='blade_1_orders', to='order_optimization.planorder')),
                ('blade_2', models.ManyToManyField(blank=True, related_name='blade_2_orders', to='order_optimization.planorder')),
            ],
        ),
    ]
