# Generated by Django 4.2.13 on 2024-08-20 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('กําหนดส่ง', models.DateTimeField(default='not defined')),
                ('แผ่นหน้า', models.CharField(default='not defined', max_length=5)),
                ('ลอน_C', models.CharField(default='not defined', max_length=5)),
                ('แผ่นกลาง', models.CharField(default='not defined', max_length=5)),
                ('ลอน_B', models.CharField(default='not defined', max_length=5)),
                ('แผ่นหลัง', models.CharField(default='not defined', max_length=5)),
                ('จน_ชั้น', models.IntegerField(default=0)),
                ('กว้างผลิต', models.IntegerField(default=0)),
                ('ยาวผลิต', models.IntegerField(default=0)),
                ('ทับเส้นซ้าย', models.IntegerField(default=0)),
                ('ทับเส้นกลาง', models.IntegerField(default=0)),
                ('ทับเส้นขวา', models.IntegerField(default=0)),
                ('เลขที่ใบสั่งขาย', models.IntegerField(default=0)),
                ('ชนิดส่วนประกอบ', models.CharField(default='not defined', max_length=5)),
                ('จํานวนสั่งขาย', models.IntegerField(default=0)),
                ('จํานวนสั่งผลิต', models.IntegerField(default=0)),
                ('ประเภททับเส้น', models.CharField(default='not defined', max_length=5)),
                ('สถานะใบสั่ง', models.CharField(default='not defined', max_length=5)),
                ('เปอร์เซ็นต์ที่เกิน', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_optimization.csvfile')),
            ],
        ),
    ]
