# Generated by Django 4.2.13 on 2024-08-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_optimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
