# Generated by Django 4.2.13 on 2024-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_optimization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='ลอน_B',
            new_name='b_wave',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='แผ่นหลัง',
            new_name='back_sheet',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='ลอน_C',
            new_name='c_wave',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='ชนิดส่วนประกอบ',
            new_name='component_type',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='กําหนดส่ง',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='ประเภททับเส้น',
            new_name='edge_type',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='เปอร์เซ็นต์ที่เกิน',
            new_name='excess_percentage',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='แผ่นหน้า',
            new_name='front_sheet',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='ทับเส้นซ้าย',
            new_name='left_edge_cut',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='ยาวผลิต',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='จน_ชั้น',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='ทับเส้นกลาง',
            new_name='middle_edge_cut',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='แผ่นกลาง',
            new_name='middle_sheet',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='จํานวนสั่งผลิต',
            new_name='production_quantity',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='จํานวนสั่งขาย',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='กว้างผลิต',
            new_name='width',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='ทับเส้นขวา',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='สถานะใบสั่ง',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='เลขที่ใบสั่งขาย',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_status',
            field=models.CharField(default='not defined', max_length=5),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='right_edge_cut',
            field=models.IntegerField(default=0),
        ),
    ]
