# Generated by Django 4.2.13 on 2024-08-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_optimization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planorder',
            name='blade_type',
            field=models.CharField(choices=[('blade_1', 'Blade 1'), ('blade_2', 'Blade 2')], default='blade_1', max_length=10),
        ),
    ]
