# Generated by Django 4.2.13 on 2024-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_optimization', '0002_rename_production_quantity_planorder_plan_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='planorder',
            name='paper_roll',
            field=models.IntegerField(default=0),
        ),
    ]
