# Generated by Django 4.2.13 on 2024-09-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_optimization', '0003_planorder_paper_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='planorder',
            name='order_leftover',
            field=models.IntegerField(default=0),
        ),
    ]
